### ISSUE TITLE
Supporting other languages

### ISSUE THREAD

**Issue by patricklynch** [AssemblyAI/realtime-transcription-browser-js-example#3]
I've been checking through the docs but I can't find where to set the `language_code` or other parameter for selecting a language other than English. Is it something added to the URL params here?
https://github.com/AssemblyAI/realtime-transcription-browser-js-example/blob/48ee7d1d58a646acc17cea152f425288767a8d7b/js/index.js#L36

THanks!

**Comment by agalyanmann** [comment]
Hey @patricklynch - sorry for the delay here! 

At this time, English is the only language available in real-time. We do have plans to add additional languages in the future! You can subscribe to our [changelog](https://changelog.assemblyai.com/) to stay updated with all new releases! Please don't hesitate to reach out with any other questions.
