### ISSUE TITLE
Specifying a language

### ISSUE THREAD

**Issue by ussuritiger** [AssemblyAI/realtime-transcription-browser-js-example#4]
From the documentation it is not clear how to specify the language of the speech while using real-time streaming transcription. Could you clarify that please? Thanks!

**Comment by agalyanmann** [comment]
Hey @ussuritiger - sorry for the delay here. Currently, real-time only supports English. We plan to expand this service to other languages on our roadmap. One way to follow along for updates is to subscribe to our changelog [here](https://changelog.assemblyai.com/)!

**Comment by frank1003A** [comment]
> Hey @ussuritiger - sorry for the delay here. Currently, real-time only supports English. We plan to expand this service to other languages on our roadmap. One way to follow along for updates is to subscribe to our changelog [here](https://changelog.assemblyai.com/)!

Hi, is this still the case now?

**Comment by agalyanmann** [comment]
Hey, @frank1003A - our streaming endpoint is English only at the moment. However, I would keep an eye on the changelog as we plan to make some updates in the future!
